<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('keuangans')->insert([
            'username' => 'keuangan',
            'password' => Crypt::encryptString('keuangan'),
            'nama' => 'Adrian',
            'user_type' => 'keuangan',
            'created_at' => Carbon::now()->subDays(15),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('pemiliks')->insert([
            'username' => 'pemilik',
            'password' => Crypt::encryptString('pemilik'),
            'nama' => 'Adnan',
            'user_type' => 'pemilik',
            'created_at' => Carbon::now()->subDays(10),
            'updated_at' => Carbon::now(),
        ]);
        DB::table('admins')->insert([
            'username' => 'admin',
            'password' => Crypt::encryptString('admin2'),
            'user_type' => 'admin',
            'created_at' => Carbon::now()->subDays(15),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('kurirs')->insert([
            [
                'username' => 'kurir',
                'password' => Crypt::encryptString('kurir'),
                'nama' => 'Adrian',
                'area_id' => '1',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(14),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir2',
                'password' => Crypt::encryptString('kurir2'),
                'nama' => 'Fadel',
                'area_id' => '1',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(14),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir3',
                'password' => Crypt::encryptString('kurir3'),
                'nama' => 'Budi',
                'area_id' => '2',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir4',
                'password' => Crypt::encryptString('kurir4'),
                'nama' => 'Citra',
                'area_id' => '2',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir5',
                'password' => Crypt::encryptString('kurir5'),
                'nama' => 'David',
                'area_id' => '3',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir6',
                'password' => Crypt::encryptString('kurir6'),
                'nama' => 'Eva',
                'area_id' => '3',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir7',
                'password' => Crypt::encryptString('kurir7'),
                'nama' => 'Farhan',
                'area_id' => '4',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir8',
                'password' => Crypt::encryptString('kurir8'),
                'nama' => 'Gita',
                'area_id' => '4',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir9',
                'password' => Crypt::encryptString('kurir9'),
                'nama' => 'Hadi',
                'area_id' => '5',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir10',
                'password' => Crypt::encryptString('kurir10'),
                'nama' => 'Ika',
                'area_id' => '5',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir11',
                'password' => Crypt::encryptString('kurir11'),
                'nama' => 'Joko',
                'area_id' => '6',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir12',
                'password' => Crypt::encryptString('kurir12'),
                'nama' => 'Kemal',
                'area_id' => '7',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir13',
                'password' => Crypt::encryptString('kurir13'),
                'nama' => 'Lia',
                'area_id' => '8',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir14',
                'password' => Crypt::encryptString('kurir14'),
                'nama' => 'Mira',
                'area_id' => '9',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir15',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => 'Nina',
                'area_id' => '10',
                'user_type' => 'kurir',
                'created_at' => now()->subDays(3),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir16',
                'password' => Crypt::encryptString('kurir16'),
                'nama' => Str::random(5),
                'area_id' => 10,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(16),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir17',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 11,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(17),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir18',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 11,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(18),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir19',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 12,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(19),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir20',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 12,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(20),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir21',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 13,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(21),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir22',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 13,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(22),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir23',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 14,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(23),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir24',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 14,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(24),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir25',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 15,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(25),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir26',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 16,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(26),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir27',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 17,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(27),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir28',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 17,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(28),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir29',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 18,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(29),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir30',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 18,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(30),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir31',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 19,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(31),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir32',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 19,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(32),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir33',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 20,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(33),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir34',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 20,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(34),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir35',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 21,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(35),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir36',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 22,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(36),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir37',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 22,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(37),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir38',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 23,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(38),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir39',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 24,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(39),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir40',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 24,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(40),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir41',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 25,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(41),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir42',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 25,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(42),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir43',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 26,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(43),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir44',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 27,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(44),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir45',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 28,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(45),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir46',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 28,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(46),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir47',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 29,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(47),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir48',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 30,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(48),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir49',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 30,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(49),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir50',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 31,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(50),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir51',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 31,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(51),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir52',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 32,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(52),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir53',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 32,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(53),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir54',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 33,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(54),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir55',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 34,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(55),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir56',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 35,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(56),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir57',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 36,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(57),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir58',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 37,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(58),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir59',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 38,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(59),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir60',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 39,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(60),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir61',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 41,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(61),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir62',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 41,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(62),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir63',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 41,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(63),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir64',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 42,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(64),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir65',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 43,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(65),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir66',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 44,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(66),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir67',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 45,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(67),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir68',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 46,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(68),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir69',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 47,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(69),
                'updated_at' => now(),
            ],
            [
                'username' => 'kurir70',
                'password' => Crypt::encryptString('kurir15'),
                'nama' => Str::random(5),
                'area_id' => 48,
                'user_type' => 'kurir',
                'created_at' => now()->subDays(70),
                'updated_at' => now(),
            ]
        ]);
    }
}
